# Generated by Django 4.2.18 on 2025-02-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=128)),
                ('achievement_description', models.CharField(max_length=512)),
                ('achievement_image', models.ImageField(upload_to='./static/main/media')),
                ('achievement_views', models.IntegerField(default=0)),
                ('achievement_upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
